config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  resources :members
  post 'match', to: 'match#calculate_rank'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/match.rb
class Match
  include ActiveModel::Model

  attr_accessor :member1, :member2, :result
end

app/models/member.rb
class Member < ApplicationRecord
  validates :name, presence: true
  validates :surname, presence: true
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i }, uniqueness: true
  validates :birthday, presence: true
  validates :games_played, presence: true
  validates :current_rank, presence: true

  def full_name_and_rank
    "#{self.name} #{self.surname} ( Rank: #{self.current_rank} )"
  end

  def full_name
    "#{self.name} #{self.surname}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/member_rank_concern.rb
module MemberRankConcern
  extend ActiveSupport::Concern

  def rank_change_up(member, ranks)
    previous_rank = member.current_rank
    new_rank = previous_rank - ranks

    Member.where(current_rank: new_rank...previous_rank).each do |other_member|
      other_member.update(current_rank: other_member.current_rank += 1)
    end

    member.update(current_rank: new_rank)
  end

  def rank_change_down(member)
    previous_rank = member.current_rank
    new_rank = previous_rank + 1

    # Update member whose spot was just taken
    other_member = Member.where(current_rank: new_rank).first
    other_member.update(current_rank: other_member.current_rank -= 1)

    member.update(current_rank: new_rank)
  end
end

app/controllers/match_controller.rb
# frozen_string_literal: true

class MatchController < ApplicationController
  include MemberRankConcern

  def calculate_rank
    member1 = Member.find(match_params[:member1])
    member2 = Member.find(match_params[:member2])

    if member1 == member2
      flash[:notice] = 'Players cannot play against themselves'
      redirect_to root_path and return
    end

    member1.update(games_played: member1.games_played += 1)
    member2.update(games_played: member2.games_played += 1)

    result = match_params[:result]

    if member1.current_rank < member2.current_rank
      higher_ranked = member1
      lower_ranked = member2
    else
      higher_ranked = member2
      lower_ranked = member1
    end

    rank_difference = (member1.current_rank - member2.current_rank).abs

    if result == 'draw' && rank_difference <= 1 ||
       result == 'member1_wins' && higher_ranked == member1 ||
       result == 'member2_wins' && higher_ranked == member2

      flash[:notice] = 'No change to ranks'
      redirect_to root_path and return
    end

    if result == 'draw'
      rank_change_up(lower_ranked, 1)
    else
      rank_change_down(higher_ranked)
      rank_change_up(lower_ranked, (rank_difference / 2).round)
    end

    flash[:notice] = 'Match successfully added'
    redirect_to root_path
  end

  private

  # Only allow a list of trusted parameters through.
  def match_params
    params.require(:match).permit(:member1, :member2, :result)
  end
end

app/controllers/members_controller.rb
# frozen_string_literal: true

class MembersController < ApplicationController
  before_action :set_member, only: %i[show edit update destroy]

  def index
    @members = Member.all
  end

  def show; end

  def new
    @member = Member.new
  end

  def edit; end

  def create
    @member = Member.new(member_params)
    @member.current_rank = Member.count + 1

    if @member.save
      redirect_to @member, notice: 'Member was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @member.update(member_params)
      redirect_to @member, notice: 'Member was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
      render json: @member.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @member.destroy
    redirect_to members_url, notice: 'Member was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_member
    @member = Member.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def member_params
    params.require(:member).permit(:name, :surname, :email, :birthday, :games_played, :current_rank)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @members = Member.all.order(current_rank: :asc)
    @leaderboard = @members.limit(10)
    @match = Match.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/layouts/_flash_messages.html.erb
<% if flash %>
  <div class="flash_message">
    <% if flash[:notice] %>
      <div class="alert alert-info">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-warning">
        <%= flash[:alert] %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChessClubAdministration</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--    before link tag to prevent bootstrap styles over riding custom styles-->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1 class="text-center">
      <i class="fas fa-chess-rook"></i>
      Anvil Chess Club
      <i class="fas fa-chess-rook"></i>
    </h1>

    <div class="text-center">
      <%= link_to 'Home', root_path %> |
      <%= link_to 'Members', members_path %>
    </div>

    <hr>

    <div class="container">
      <%= render partial: "layouts/flash_messages" %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/members/_form.html.erb
<%= simple_form_for(@member) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <div class="row">
      <div class="col-md-6"><%= f.input :name %></div>
      <div class="col-md-6"><%= f.input :surname %></div>
      <div class="col-md-6"><%= f.input :email %></div>
      <div class="col-md-6"><%= f.input :birthday %></div>
    </div>
  </div>

  <div class="form-actions my-2">
    <%= f.button :submit, class: 'btn btn-success' %>
    <%= link_to 'Cancel', :back, class: "btn btn-warning", data: { confirm: 'Are you sure?'} %>
  </div>
<% end %>

app/views/members/edit.html.erb
<div class="form_container box">
  <h1>Editing Member</h1>

  <%= render 'form', member: @member %>
</div>

app/views/members/index.html.erb
<h1>Members</h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Rank</th>
      <th scope="col">Name</th>
      <th scope="col">Surname</th>
      <th scope="col">Games Played</th>
      <th scope="col">Email</th>
      <th scope="col">Birthday</th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <th scope="row"><%= member.current_rank %></th>
        <td><%= member.name %></td>
        <td><%= member.surname %></td>
        <td><%= member.games_played %></td>
        <td><%= member.email %></td>
        <td><%= member.birthday %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Member', new_member_path, class: "btn btn-success" %>

app/views/members/new.html.erb
<div class="form_container">
  <h1>New Member</h1>

  <%= render 'form', member: @member %>
</div>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @member.surname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @member.email %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @member.birthday %>
</p>

<p>
  <strong>Games played:</strong>
  <%= @member.games_played %>
</p>

<p>
  <strong>Current rank:</strong>
  <%= @member.current_rank %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>

app/views/pages/_leaderboard.html.erb
<h2>Leaderboard</h2>

<table class="table">
  <thead class="thead-dark">
  <tr>
    <th scope="col">Rank</th>
    <th scope="col">Name</th>
    <th scope="col">Games Played</th>
  </tr>
  </thead>

  <tbody>
  <% @leaderboard.each do |member| %>
    <tr>
      <th scope="row"><%= member.current_rank %></th>
      <td><%= member.full_name %></td>
      <td><%= member.games_played %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/pages/_match_up_form.html.erb
<%= simple_form_for @match, url: match_path, method: :post do |f| %>
  <div class="form-inputs">
    <div class="row">
      <%= f.error_notification %>
      <div class="col-md-5">
        <%= f.input :member1, collection: @members, label_method: :full_name_and_rank, include_blank: false, include_hidden: false %>
      </div>

      <div class="col-md-2 vs_text">VS</div>

      <div class="col-md-5">
        <%= f.input :member2, collection: @members, label_method: :full_name_and_rank, include_blank: false, include_hidden: false %>
      </div>

      <%= f.input :result, collection: [['Member 1 Won', 'member1_wins'],['Member 2 Won', 'member2_wins'] , ['Draw', 'draw']], include_blank: false, include_hidden: false %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Add Match', class: 'btn btn-success my-2' %>
  </div>
<% end %>

app/views/pages/home.html.erb
<div class="row">
  <div class="col-8">
    <div class="box">
      <h2>Match up</h2>

      <%= render partial: 'pages/match_up_form' %>
    </div>
  </div>

  <div class="col-4">
    <div class="box">
      <%= render partial: 'pages/leaderboard' %>
    </div>
  </div>
</div>